model_extensions_dir: <%= File.join(Rails.application.config.rocci_server_etc_dir, 'backends', 'ec2', 'model') %>
fixtures_dir: <%= File.join(Rails.application.config.rocci_server_etc_dir, 'backends', 'ec2', 'fixtures') %>
access_key_id: <%= ENV['ROCCI_SERVER_EC2_AWS_ACCESS_KEY_ID'] %>
secret_access_key: <%= ENV['ROCCI_SERVER_EC2_AWS_SECRET_ACCESS_KEY'] %>
aws_region: <%= ENV['ROCCI_SERVER_EC2_AWS_REGION'] || 'eu-west-1' %>
aws_endpoint: <%= ENV['ROCCI_SERVER_EC2_AWS_ENDPOINT'] || '' %>  # Do NOT change this value unless you know exactly what you are doing!
aws_availability_zone: <%= ENV['ROCCI_SERVER_EC2_AWS_AVAILABILITY_ZONE'] || 'eu-west-1a' %>
image_filtering:
  policy: <%= ENV['ROCCI_SERVER_EC2_IMAGE_FILTERING_POLICY'] || 'all' %>  # 'only_listed' or 'only_owned' or 'owned_and_listed' or 'all'
  image_list: <%= ENV['ROCCI_SERVER_EC2_IMAGE_FILTERING_IMAGE_LIST'] || '' %>
network_create_allowed: <%= ENV['ROCCI_SERVER_EC2_NETWORK_CREATE_ALLOWED'].blank? ? 'false' : ENV['ROCCI_SERVER_EC2_NETWORK_CREATE_ALLOWED'] %>
network_destroy_allowed: <%= ENV['ROCCI_SERVER_EC2_NETWORK_DESTROY_ALLOWED'].blank? ? 'false' : ENV['ROCCI_SERVER_EC2_NETWORK_DESTROY_ALLOWED'] %>
network_destroy_vpn_gws: <%= ENV['ROCCI_SERVER_EC2_NETWORK_DESTROY_VPN_GWS'].blank? ? 'false' : ENV['ROCCI_SERVER_EC2_NETWORK_DESTROY_VPN_GWS'] %>
vo_aws_mapfile: <%= ENV['ROCCI_SERVER_EC2_VO_AWS_MAPFILE'] || '' %>
